- hosts: dev
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: latest
    - name: Ensure apache is running
      service:
        name: httpd
        state: started
    - name: Copy index file
      template:
        src: /root/website/index.html.j2
        dest: /var/www/html/index.html
    - name: apache listen on port 8080
      lineinfile: dest=/etc/httpd/conf/httpd.conf regexp="^Listen 80" line="Listen 8080" state="present"
      notify:
        - restart httpd
  handlers:
    - name: restart httpd
      service: name=httpd state=restarted enabled=true
